package MyAnswer;

import textio.TextIO;

/**This class uses to test BlackjackHand class. It creates
 * a deck within 54 cards in a random order. This deck includes
 * two jokers as well. Then, it generates a random number from 2
 * to 6 which is the number of the hands. The cards in hands are assigned
 * from the deck. Finally, it will output all the cards from the hands and
 * the blackjack value of the hands. This class depends on the BlackjackHand class,
 * Card class, Deck class, Hand class and TextIO class.
 * */
public class Main {

	public static void main(String[] args) {
		
		TextIO.put("Starting Game? (y or n):");
		boolean userResponse = TextIO.getlnBoolean();	//Obtaining the user response for the first game
		
		while(userResponse)
		{
			playGame();
			TextIO.put("Starting Another Game? (y or n):");
			userResponse = TextIO.getlnBoolean();	//Obtaining the user response of whether the user
													//wants to continue or not.
		}

	}	//end of main
	
	/**This subroutine will generate a deck with 54 random order cards,
	 * and assign a specific number of cards to the hands. The size of 
	 * hands is generated by a random number from 2 to 6. Finally, it outputs
	 * all the cards that hands have and the blackjack value of the hands. 
	 * */
	public static void playGame() 
	{
		Deck dk = new Deck(true);	//Generate 54 cards in a sorted order 		
		dk.shuffle(); 		//Making 54 cards in a random order
		
		/*Generate a random value from 2 to 6*/
		int randomNumberOfHandCards = (int)(Math.random()*6) + 1;
		
		if(randomNumberOfHandCards == 1)
		{
			randomNumberOfHandCards++;
		}
		
		/*Generating a hand and remove all the cards that hand have*/
		BlackjackHand bjk = new BlackjackHand();
		bjk.clear();
		
		/*Printing out all the cards that have assigned to the hand*/
		System.out.println("\nCards:");
		for(int i = 0; i < randomNumberOfHandCards; i++)
		{			
			bjk.addCard(dk.dealCard());
			System.out.println(bjk.getCard(i));
		}
		
		/*Printing out the blackjack value of the hand*/
		System.out.println("\nBlackjack Value:");
		System.out.println(bjk.getBlackjackValue());
		System.out.println();
	}

}
